### PR TITLE
Fall back on tag_name if release has no name

### PR DESCRIPTION
**Pull request by dolphinspired**
Hey, just found your site today as I was learning the GitHub API. Thanks for putting this together!

There's one small suggestion I'd like to make. On the GitHub releases page, if you don't give your release a "name", then it will populate the header with the release's "tag_name" instead. I had not been giving my releases names in one repo, so my API responses came back looking like this:

```json
{
  "name": "",
  "tag_name": "v1.2.0"
}
```

...which resulted in a bunch of unnamed releases in your download counter.

So my suggestion is simply to copy what the Releases page does and fall back on "tag_name" if "name" is empty when grouping download numbers. Here's a super-quick, untested solution to implement that - take it if you'd like! And feel free to use [this repo](https://github.com/runeberry/PlayerMadeQuests) to test it out.

### CODE REVIEW

**Comment by dr-nyt** [comment]
Apologies for the delayed response, I didn't realize there was a pull request. I'll check it out and get back to you soon.

**Review by dr-nyt — CHANGES_REQUESTED** [review]
Just tested it, you will need to add || instead of ?? for this to work, could you make that change and I'll approve your pull request.

**Comment by dolphinspired** [comment]
Hey, thanks for the review! Made the change. (I've been doing a lot of C# recently, so I got my wires crossed)

**Review by dr-nyt — APPROVED** [review]

**Comment by dr-nyt** [comment]
I get confused with language syntax all the time too, but thanks for fixing the bug, greatly appreciated! 👍

**Pull request merged**
